# Generated by Django 5.2 on 2025-04-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
